// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzoU71pPAY7bI3nQoxuc-dfhFSfk8COF4',
    appId: '1:561155944910:web:56870e55d78e19b92dfb9f',
    messagingSenderId: '561155944910',
    projectId: 'firelogincrud-f486d',
    authDomain: 'firelogincrud-f486d.firebaseapp.com',
    storageBucket: 'firelogincrud-f486d.appspot.com',
    measurementId: 'G-TJRD76X62T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC11tRtvjj5rMHX4X1xZuCSyYAU2_wMP_0',
    appId: '1:561155944910:android:d39da06f9cc7e84f2dfb9f',
    messagingSenderId: '561155944910',
    projectId: 'firelogincrud-f486d',
    storageBucket: 'firelogincrud-f486d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHMDYn42frBBdYdnsavMqMQr5P7_JZ76A',
    appId: '1:561155944910:ios:98eb01c69710f7a72dfb9f',
    messagingSenderId: '561155944910',
    projectId: 'firelogincrud-f486d',
    storageBucket: 'firelogincrud-f486d.appspot.com',
    iosClientId: '561155944910-ocfg51j0nbs6fitooierkbanmu15nto5.apps.googleusercontent.com',
    iosBundleId: 'pe.edu.upeu.asistenciaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHMDYn42frBBdYdnsavMqMQr5P7_JZ76A',
    appId: '1:561155944910:ios:34c189576e8effde2dfb9f',
    messagingSenderId: '561155944910',
    projectId: 'firelogincrud-f486d',
    storageBucket: 'firelogincrud-f486d.appspot.com',
    iosClientId: '561155944910-4oa9pq0h00va7u160kbn9s4j3buf7d43.apps.googleusercontent.com',
    iosBundleId: 'pe.edu.upeu.asistenciaApp.RunnerTests',
  );
}
